// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: fabricx/migration/v1/genesis_data.proto

package genesisdata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StateRecord is one public Fabric state entry mapped to a Fabric-X namespace.
type StateRecord struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	SourceNamespace         string                 `protobuf:"bytes,1,opt,name=source_namespace,json=sourceNamespace,proto3" json:"source_namespace,omitempty"`
	TargetNamespace         string                 `protobuf:"bytes,2,opt,name=target_namespace,json=targetNamespace,proto3" json:"target_namespace,omitempty"`
	Key                     []byte                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value                   []byte                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Metadata                []byte                 `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	SourceVersion           []byte                 `protobuf:"bytes,6,opt,name=source_version,json=sourceVersion,proto3" json:"source_version,omitempty"`
	SourceBlockNumber       uint64                 `protobuf:"varint,7,opt,name=source_block_number,json=sourceBlockNumber,proto3" json:"source_block_number,omitempty"`
	SourceTransactionNumber uint64                 `protobuf:"varint,8,opt,name=source_transaction_number,json=sourceTransactionNumber,proto3" json:"source_transaction_number,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *StateRecord) Reset() {
	*x = StateRecord{}
	mi := &file_fabricx_migration_v1_genesis_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateRecord) ProtoMessage() {}

func (x *StateRecord) ProtoReflect() protoreflect.Message {
	mi := &file_fabricx_migration_v1_genesis_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateRecord.ProtoReflect.Descriptor instead.
func (*StateRecord) Descriptor() ([]byte, []int) {
	return file_fabricx_migration_v1_genesis_data_proto_rawDescGZIP(), []int{0}
}

func (x *StateRecord) GetSourceNamespace() string {
	if x != nil {
		return x.SourceNamespace
	}
	return ""
}

func (x *StateRecord) GetTargetNamespace() string {
	if x != nil {
		return x.TargetNamespace
	}
	return ""
}

func (x *StateRecord) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *StateRecord) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *StateRecord) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *StateRecord) GetSourceVersion() []byte {
	if x != nil {
		return x.SourceVersion
	}
	return nil
}

func (x *StateRecord) GetSourceBlockNumber() uint64 {
	if x != nil {
		return x.SourceBlockNumber
	}
	return 0
}

func (x *StateRecord) GetSourceTransactionNumber() uint64 {
	if x != nil {
		return x.SourceTransactionNumber
	}
	return 0
}

var File_fabricx_migration_v1_genesis_data_proto protoreflect.FileDescriptor

const file_fabricx_migration_v1_genesis_data_proto_rawDesc = "" +
	"\n" +
	"'fabricx/migration/v1/genesis_data.proto\x12\x14fabricx.migration.v1\"\xba\x02\n" +
	"\vStateRecord\x12)\n" +
	"\x10source_namespace\x18\x01 \x01(\tR\x0fsourceNamespace\x12)\n" +
	"\x10target_namespace\x18\x02 \x01(\tR\x0ftargetNamespace\x12\x10\n" +
	"\x03key\x18\x03 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x04 \x01(\fR\x05value\x12\x1a\n" +
	"\bmetadata\x18\x05 \x01(\fR\bmetadata\x12%\n" +
	"\x0esource_version\x18\x06 \x01(\fR\rsourceVersion\x12.\n" +
	"\x13source_block_number\x18\a \x01(\x04R\x11sourceBlockNumber\x12:\n" +
	"\x19source_transaction_number\x18\b \x01(\x04R\x17sourceTransactionNumberB8Z6github.com/syndbg/fabric-x-migrate-poc/pkg/genesisdatab\x06proto3"

var (
	file_fabricx_migration_v1_genesis_data_proto_rawDescOnce sync.Once
	file_fabricx_migration_v1_genesis_data_proto_rawDescData []byte
)

func file_fabricx_migration_v1_genesis_data_proto_rawDescGZIP() []byte {
	file_fabricx_migration_v1_genesis_data_proto_rawDescOnce.Do(func() {
		file_fabricx_migration_v1_genesis_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fabricx_migration_v1_genesis_data_proto_rawDesc), len(file_fabricx_migration_v1_genesis_data_proto_rawDesc)))
	})
	return file_fabricx_migration_v1_genesis_data_proto_rawDescData
}

var file_fabricx_migration_v1_genesis_data_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_fabricx_migration_v1_genesis_data_proto_goTypes = []any{
	(*StateRecord)(nil), // 0: fabricx.migration.v1.StateRecord
}
var file_fabricx_migration_v1_genesis_data_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fabricx_migration_v1_genesis_data_proto_init() }
func file_fabricx_migration_v1_genesis_data_proto_init() {
	if File_fabricx_migration_v1_genesis_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fabricx_migration_v1_genesis_data_proto_rawDesc), len(file_fabricx_migration_v1_genesis_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fabricx_migration_v1_genesis_data_proto_goTypes,
		DependencyIndexes: file_fabricx_migration_v1_genesis_data_proto_depIdxs,
		MessageInfos:      file_fabricx_migration_v1_genesis_data_proto_msgTypes,
	}.Build()
	File_fabricx_migration_v1_genesis_data_proto = out.File
	file_fabricx_migration_v1_genesis_data_proto_goTypes = nil
	file_fabricx_migration_v1_genesis_data_proto_depIdxs = nil
}
