// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: fabricx/migration/v1/transaction_id.proto

package genesisdata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TransactionIDRecord preserves a source transaction ID for anti-replay.
// A Fabric snapshot does not provide its validation status or block position.
type TransactionIDRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionIDRecord) Reset() {
	*x = TransactionIDRecord{}
	mi := &file_fabricx_migration_v1_transaction_id_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionIDRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionIDRecord) ProtoMessage() {}

func (x *TransactionIDRecord) ProtoReflect() protoreflect.Message {
	mi := &file_fabricx_migration_v1_transaction_id_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionIDRecord.ProtoReflect.Descriptor instead.
func (*TransactionIDRecord) Descriptor() ([]byte, []int) {
	return file_fabricx_migration_v1_transaction_id_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionIDRecord) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

var File_fabricx_migration_v1_transaction_id_proto protoreflect.FileDescriptor

const file_fabricx_migration_v1_transaction_id_proto_rawDesc = "" +
	"\n" +
	")fabricx/migration/v1/transaction_id.proto\x12\x14fabricx.migration.v1\"<\n" +
	"\x13TransactionIDRecord\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionIdB8Z6github.com/syndbg/fabric-x-migrate-poc/pkg/genesisdatab\x06proto3"

var (
	file_fabricx_migration_v1_transaction_id_proto_rawDescOnce sync.Once
	file_fabricx_migration_v1_transaction_id_proto_rawDescData []byte
)

func file_fabricx_migration_v1_transaction_id_proto_rawDescGZIP() []byte {
	file_fabricx_migration_v1_transaction_id_proto_rawDescOnce.Do(func() {
		file_fabricx_migration_v1_transaction_id_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fabricx_migration_v1_transaction_id_proto_rawDesc), len(file_fabricx_migration_v1_transaction_id_proto_rawDesc)))
	})
	return file_fabricx_migration_v1_transaction_id_proto_rawDescData
}

var file_fabricx_migration_v1_transaction_id_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_fabricx_migration_v1_transaction_id_proto_goTypes = []any{
	(*TransactionIDRecord)(nil), // 0: fabricx.migration.v1.TransactionIDRecord
}
var file_fabricx_migration_v1_transaction_id_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fabricx_migration_v1_transaction_id_proto_init() }
func file_fabricx_migration_v1_transaction_id_proto_init() {
	if File_fabricx_migration_v1_transaction_id_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fabricx_migration_v1_transaction_id_proto_rawDesc), len(file_fabricx_migration_v1_transaction_id_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fabricx_migration_v1_transaction_id_proto_goTypes,
		DependencyIndexes: file_fabricx_migration_v1_transaction_id_proto_depIdxs,
		MessageInfos:      file_fabricx_migration_v1_transaction_id_proto_msgTypes,
	}.Build()
	File_fabricx_migration_v1_transaction_id_proto = out.File
	file_fabricx_migration_v1_transaction_id_proto_goTypes = nil
	file_fabricx_migration_v1_transaction_id_proto_depIdxs = nil
}
